services:
  mysql:
    container_name: carnation_mysql_container
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    container_name: carnation_redis_container
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server --requirepass ${REDIS_PASSWORD}

  server:
    container_name: carnation_server_container
    image: kkm4512/carnation
    ports:
      - 8080:8080
    depends_on:
      - mysql
      - redis
    restart: always
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prd

volumes:
  mysql_data:
  redis_data:
