server:
  profiles:
    active: dev,prd

spring:
  servlet:
    multipart:
      enabled: ${MULTIPART_ENABLED}
      max-file-size: ${MULTIPART_MAX_FILE_SIZE}
      max-request-size: ${MULTIPART_MAX_REQUEST_SIZE}

# JWT
jwt:
  secret:
    key: ${JWT_SECRET_KEY}

springdoc:
  swagger-ui:
    path: /docs
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  writer-with-default-pretty-printer: true
  model-and-view-allowed: true

# AWS S3 config
cloud:
  aws:
    s3:
      bucket: ${AWS_BUCKET}
    stack.auto: false
    region.static: ${AWS_REGION_STATIC}
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}


