server:
  port: ${SERVER_DEPLOY_PORT}

swagger:
  server-url: ${SERVER_DEPLOY_URL}

# DB config
spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_DEPLOY_HOST}:${MYSQL_DEPLOY_PORT}/${MYSQL_DB_NAME}?serverTimezone=Asia/Seoul
    username: ${MYSQL_NAME}
    password: ${MYSQL_PASSWORD}
  # DB update
  jpa:
    hibernate:
      ddl-auto: update
      # sql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true

social:
  redirect:
    url: ${SOCIAL_REDIRECT_URL_DEPLOY}
