server:
  profiles:
    active: dev,prd

# JWT
jwt:
  secret:
    key: ${JWT_SECRET_KEY}

springdoc:
  swagger-ui:
    path: /docs
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    display-request-duration: true
    defaultModelsExpandDepth: 2
    defaultModelExpandDepth: 2
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true
  model-and-view-allowed: true

# AWS S3 config
cloud:
  aws:
    s3:
      bucket: ${AWS_BUCKET}
    stack.auto: false
    region.static: ${AWS_REGION_STATIC}
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}


