server:
  profiles:
    active: dev,prd

spring:
  servlet:
    multipart:
      enabled: ${MULTIPART_ENABLED}
      max-file-size: ${MULTIPART_MAX_FILE_SIZE}
      max-request-size: ${MULTIPART_MAX_REQUEST_SIZE}
  data:
    redis:
      password: ${REDIS_PASSWORD}

# JWT
jwt:
  secret:
    key: ${JWT_SECRET_KEY}

springdoc:
  swagger-ui:
    path: /docs
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  writer-with-default-pretty-printer: true
  model-and-view-allowed: true

# AWS S3 config
cloud:
  aws:
    s3:
      bucket: ${AWS_BUCKET}
    stack.auto: false
    region.static: ${AWS_REGION_STATIC}
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}

social:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
  naver:
    client-id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_CLIENT_SECRET}
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    scope:
      - email
      - profile
      -
coolsms:
  api:
    key: ${COOLSMS_KEY}
    secret: ${COOLSMS_SECRET_KEY}
    fromNumber: ${COOLSMS_FROM_PHONE_NUMBER}
    url: ${COOLSMS_URL}



